### ISSUE TITLE
Module not found: Error: Can't resolve 

### ISSUE THREAD

**Issue by shapesim** [chuckbergeron/etherplate#10]
Hi. Getting many errors with 'npm run dev' on Windows. Please help. The only thing I change for the project is modify truffle.js to use my full node on my local machine with geth, instead of infura.io, which doesn't work for me. Below is the full print out of errors

> PS C:\Users\zfore\Documents\github\etherplate> npm run dev
> 
> > etherplate@0.0.1 dev C:\Users\zfore\Documents\github\etherplate
> > webpack-dev-server --config webpack.dev.js --mode development
> 
> i ｢wds｣: Project is running at http://localhost:8080/
> i ｢wds｣: webpack output is served from /
> i ｢wds｣: 404s will fallback to /index.html
> × ｢wdm｣: Hash: 7e3327a876e4e89771ee
> Version: webpack 4.16.0
> Time: 9911ms
> Built at: 2018-07-16 00:42:06
>                                           Asset       Size  Chunks             Chunk Names
>            images/button--download-metamask.png   72.7 KiB          [emitted]
>                                          app.js   3.28 MiB    main  [emitted]  main
>                                      _redirects   25 bytes          [emitted]
>                                      index.html  618 bytes          [emitted]
>                    images/button--app-store.png   3.87 KiB          [emitted]
>                   images/avatar-placeholder.png  528 bytes          [emitted]
>                   images/button--play-store.png    4.2 KiB          [emitted]
>       images/logos/etherplate-logo--red--lg.png   96.5 KiB          [emitted]
>                                      app.js.map   3.48 MiB    main  [emitted]  main
>     images/logos/etherplate-logo--white--lg.png   75.8 KiB          [emitted]
>                          images/placeholder.png   53.7 KiB          [emitted]
>                      images/etherplate-demo.gif    920 KiB          [emitted]
> images/token-images/icons-shield--1024-1024.png   95.5 KiB          [emitted]
>    images/token-images/icons-sword--128-128.png   3.75 KiB          [emitted]
>  images/token-images/icons-sword--1024-1024.png   53.7 KiB          [emitted]
>   images/token-images/icons-shield--128-128.png   8.28 KiB          [emitted]
> Entrypoint main = app.js app.js.map
> [./app/javascripts/app.js] 1.9 KiB {main} [built]
> [./app/javascripts/init.jsx] 796 bytes {main} [built]
> [./node_modules/@babel/polyfill/lib/index.js] 527 bytes {main} [built]
> [./node_modules/@babel/polyfill/node_modules/core-js/shim.js] 7.99 KiB {main} [built]
> [./node_modules/regenerator-runtime/runtime.js] 23.6 KiB {main} [built]
> [./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
> [./node_modules/url/url.js] 22.8 KiB {main} [built]
> [./node_modules/web3/index.js] 193 bytes {main} [built]
> [./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.75 KiB {main} [built]
> [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
> [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
> [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {main} [built]
> [0] multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js 52 bytes {main} [built]
> [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
> [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {main} [built]
>     + 574 hidden modules
> 
> ERROR in ./app/javascripts/components/application/layout/header/index.jsx
> Module not found: Error: Can't resolve './app/images/logos/etherplate-logo--white--lg.png' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\layout\header'
>  @ ./app/javascripts/components/application/layout/header/index.jsx 16:52-112
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token-list/token-list-item.jsx
> Module not found: Error: Can't resolve './app/images/placeholder.png' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token-list'
>  @ ./app/javascripts/components/application/token-list/token-list-item.jsx 22:42-81
>  @ ./app/javascripts/components/application/token-list/index.jsx
>  @ ./app/javascripts/components/application/all-tokens.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/EtherscanButton' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token'
>  @ ./app/javascripts/components/application/token/index.jsx 22:46-101
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/address' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token'
>  @ ./app/javascripts/components/application/token/index.jsx 20:38-85
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token-list/token-list-item.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/address' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token-list'
>  @ ./app/javascripts/components/application/token-list/token-list-item.jsx 16:15-62
>  @ ./app/javascripts/components/application/token-list/index.jsx
>  @ ./app/javascripts/components/application/all-tokens.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/layout/header/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/application/layout/header/NetworkInfo' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\layout\header'
>  @ ./app/javascripts/components/application/layout/header/index.jsx 14:42-119
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/customize-token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/ether' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\customize-token'
>  @ ./app/javascripts/components/application/customize-token/index.jsx 26:36-81
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/landing.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/hero' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application'
>  @ ./app/javascripts/components/application/landing.jsx 12:35-79
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/not-found/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/hero' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\not-found'
>  @ ./app/javascripts/components/application/not-found/index.jsx 10:35-79
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/purchase-history/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/hero' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\purchase-history'
>  @ ./app/javascripts/components/application/purchase-history/index.jsx 16:35-79
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token-list/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/hero' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token-list'
>  @ ./app/javascripts/components/application/token-list/index.jsx 14:35-79
>  @ ./app/javascripts/components/application/all-tokens.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token-list/token-list-item.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/loading' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token-list'
>  @ ./app/javascripts/components/application/token-list/token-list-item.jsx 14:38-85
>  @ ./app/javascripts/components/application/token-list/index.jsx
>  @ ./app/javascripts/components/application/all-tokens.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/components/web3Wrap' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application'
>  @ ./app/javascripts/components/application/index.jsx 24:39-87
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/contracts/nfTokenFactory' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application'
>  @ ./app/javascripts/components/application/index.jsx 22:45-98
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/customize-token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/contracts/nfTokenFactory' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\customize-token'
>  @ ./app/javascripts/components/application/customize-token/index.jsx 20:45-98
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/purchase-history/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/contracts/nfTokenFactory' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\purchase-history'
>  @ ./app/javascripts/components/application/purchase-history/index.jsx 12:45-98
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/redux/actions' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application'
>  @ ./app/javascripts/components/application/index.jsx 18:15-57
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/customize-token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/redux/actions' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\customize-token'
>  @ ./app/javascripts/components/application/customize-token/index.jsx 22:15-57
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/redux/reducers' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application'
>  @ ./app/javascripts/components/application/index.jsx 20:16-59
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/purchase-history/token-row.jsx
> Module not found: Error: Can't resolve './app/javascripts/services/get-token' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\purchase-history'
>  @ ./app/javascripts/components/application/purchase-history/token-row.jsx 14:39-86
>  @ ./app/javascripts/components/application/purchase-history/index.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/services/get-token' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token'
>  @ ./app/javascripts/components/application/token/index.jsx 26:39-86
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token-list/token-list-item.jsx
> Module not found: Error: Can't resolve './app/javascripts/services/get-token' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token-list'
>  @ ./app/javascripts/components/application/token-list/token-list-item.jsx 20:39-86
>  @ ./app/javascripts/components/application/token-list/index.jsx
>  @ ./app/javascripts/components/application/all-tokens.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/customize-token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/services/nfToken-type-image-url' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\customize-token'
>  @ ./app/javascripts/components/application/customize-token/index.jsx 28:50-110
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/purchase-history/token-row.jsx
> Module not found: Error: Can't resolve './app/javascripts/services/nfToken-type-image-url' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\purchase-history'
>  @ ./app/javascripts/components/application/purchase-history/token-row.jsx 16:50-110
>  @ ./app/javascripts/components/application/purchase-history/index.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token/index.jsx
> Module not found: Error: Can't resolve './app/javascripts/services/nfToken-type-image-url' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token'
>  @ ./app/javascripts/components/application/token/index.jsx 24:50-110
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> 
> ERROR in ./app/javascripts/components/application/token-list/token-list-item.jsx
> Module not found: Error: Can't resolve './app/javascripts/services/nfToken-type-image-url' in 'C:\Users\zfore\Documents\github\etherplate\app\javascripts\components\application\token-list'
>  @ ./app/javascripts/components/application/token-list/token-list-item.jsx 18:50-110
>  @ ./app/javascripts/components/application/token-list/index.jsx
>  @ ./app/javascripts/components/application/all-tokens.jsx
>  @ ./app/javascripts/components/application/index.jsx
>  @ ./app/javascripts/init.jsx
>  @ ./app/javascripts/app.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080 @babel/polyfill ./app/javascripts/app.js
> i ｢wdm｣: Failed to compile.

**Comment by chuckbergeron** [comment]
I gave this a shot and couldn't even get webpack to run in Powershell or cmd.exe. I'd recommend using Unix Subsystem for Windows instead 😀
